[project]
name = "foxypack"
version = "0.0.6.1"
description = "foxy interface library, entity balancing core, and shared parser"
authors = [
    {name = "shapdi", email = "shapranov.work@gmail.com"},
]
dependencies = ["pydantic==2.11.7"]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[project.urls]
repository = "https://github.com/ShapDi/foxypack"

[project.optional-dependencies]
test = [
    "coverage>=7.10.7",
    "mypy>=1.18.2",
    "pytest>=8.4.2",
    "ruff>=0.13.2",
]
docs = [
    "mkdocs-material>=9.6.22",
    "mkdocs-static-i18n[material]>=1.3.0",
]
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
